apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    purpose: demonstrate-install
spec:
  containers:
  - name: demo-container
    image: quay.io/rocrisp/install-operators:v1.0
  restartPolicy: OnFailure