apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    purpose: demonstrate-install
spec:
  containers:
  - name: demo-container
    image: quay.io/rocrisp/install-operators:v0.1
    command: ["bin/run.sh"]
  restartPolicy: OnFailure