apiVersion: batch/v1
kind: Job
metadata:
  generateName: operator-audit-
spec:
  template:
    metadata:
      name: operator-audit
    spec:
      containers:
        - name: operator-audit
          image: quay.io/john_mckenzie/operator-install-audit:latest
          imagePullPolicy: Always
      restartPolicy: Never
